export const privacy = {
    'title'  : 'Terms and Conditions',
    'content': '<ol>' + 
    '<li>Introduction<br /><br />The Terms of Use of the Llamagard website include these Terms and Conditions, the Privacy Policy and any other terms and conditions that appear in or are linked to the Llamagard website (Additional Terms and Conditions).<br /><br /></li>' +
    '<li>Website content and access<br /><br />While Llamagard Pty Limited endeavours to take reasonable care in preparing and maintaining the information on this website we do not warrant the accuracy, reliability, adequacy or completeness of any of the website content. You acknowledge and accept that the website content may include technical inaccuracies and typographical errors. The website content is subject to change at any time without notice and may not necessarily be up to date or accurate at the time you view it.<br /><br />It is your responsibility to enquire with us directly to ensure the accuracy and currency of the material or information you seek to rely upon. To the extent permitted by law, including the Competition and Consumer Act 2010 (Cth), Llamagard Pty Limited disclaims all liability for loss directly or indirectly arising from your use of or reliance on the website and the website content.<br />Llamagard Pty Limited does not guarantee that access to the Llamagard website will be uninterrupted or that the website is free from viruses or anything else which may damage any computer which accesses the Llamagard website or any data on such a computer.<br /><br /></li>' +
    '<li>Limitation of liability<br /><br />To the maximum extent permitted by law Llamagard Pty Limited excludes all liability for any loss or damage of any kind (including special, indirect or consequential loss and including loss of business profits) arising out of or in connection with the website content and the use or performance of the Llamagard website except to the extent that the loss or damage is directly caused by Llamagard Pty Limited&rsquo;s fraud or wilful misconduct.<br />Where the law, including without limitation the Competition and Consumer Act 2010 (Cth), implies a warranty or guarantee into these website Terms and Conditions which may not lawfully be excluded, then provided it is fair and reasonable to do so, Llamagard Pty Limited\'s liability for breach of such a warranty or guarantee shall be limited at its option, to resupply the services or payment of the cost of having the services supplied again.<br /><br /></li>' +
    '<li>Intellectual property<br /><br />The materials displayed on this website, including without limitation all editorial materials, information, photographs, illustrations, artwork and other graphic materials, and names, logos and trademarks, are the property of Llamagard Pty Limited and are protected by copyright, trade mark and other intellectual property laws. Any such content may be displayed and printed solely for your personal, non-commercial use within your organisation provided that any copyright notice on such a display or page is not removed. You agree not to reproduce, retransmit, distribute, disseminate, sell, publish, broadcast or circulate any such material to any third party without the express prior written consent of Llamagard Pty Limited.<br />Save for the above, and unless expressly granted, Llamagard Pty Limited does not grant any licence or right in, or assign all or part of, its intellectual property rights in the content or applications incorporated into the Llamagard website or in the user interface of the Llamagard website.<br /><br /></li>' +
    '<li>Submissions<br /><br />Any material you send to us on or via the Llamagard website will be deemed to be non-confidential and non-proprietary, unless it is indicated to be otherwise. This includes any data, questions, comments, suggestions, ideas or other information. We will be entitled to use any such material which has not been indicated to be confidential or proprietary for any purpose without compensation to you.<br /><br /></li>' +
    '<li>Third party websites<br /><br />The Llamagard website may contain links to other websites operated, controlled or produced by third parties. Unless otherwise indicated, Llamagard Pty Limited does not control, endorse, sponsor or approve any such third party websites or their content nor does Llamagard Pty Limited provide any warranty or take any responsibility whatsoever for any aspect of those websites or their content.<br /><br /></li>' +
    '<li>Links to Llamagard website<br /><br />If you wish to establish a link to this website, you must first seek approval from Llamagard. To seek approval, please contact&nbsp;<a href="mailto:contact@llamagard.com">contact@llamagard.com</a>.<br />The following information will be required to assess your request: the URL of the website that you seek to establish a link from, a brief description of your website and the reason that you wish to establish a link.<br />If Llamagard Pty Limited agrees to your proposed link, you must comply with any terms and conditions imposed by Llamagard Pty Limited as a condition of such agreement. If the nature and/or content of your website changes in any significant way, you must contact Llamagard Pty Limited and provide a new description of your website. <br /><br /></li>' +
    '<li>Interference with website<br /><br />You must not attempt to change, add to, remove, deface, hack or otherwise interfere with this website or any material or content displayed on the Llamagard website. <br />&nbsp;</li>' +
    '<li>Jurisdiction<br /><br />These Terms and Conditions are governed by and construed in accordance with the State of Queensland, Australia. In the event that a dispute arises from these Website Terms and Conditions, each of Llamagard Pty Limited and you agree to submit to the non-exclusive jurisdiction of the courts of Queensland, Australia.</li>'+
    '</ol>'
}
